# Generated by Django 3.0.3 on 2020-03-16 21:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label_name', models.CharField(max_length=100, verbose_name='标签名称')),
                ('label_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='标签所属用户')),
            ],
            options={
                'verbose_name': '文献标签',
                'verbose_name_plural': '文献标签',
            },
        ),
        migrations.CreateModel(
            name='Literature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('literature_name', models.CharField(max_length=100, verbose_name='文献标题')),
                ('literature_author', models.CharField(max_length=100, verbose_name='文献作者')),
                ('literature_like', models.IntegerField(default=0, verbose_name='文献点赞数')),
                ('literature_download', models.IntegerField(default=0, verbose_name='文献下载次数')),
                ('literature_file', models.FileField(upload_to='upload/literatures/', verbose_name='文献文件')),
                ('filename', models.TextField(default='', verbose_name='文献的文件名')),
                ('filesize', models.IntegerField(default=0, verbose_name='文献大小')),
                ('upload_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='文献上传时间')),
                ('literature_label', models.ManyToManyField(blank=True, to='literature.Label', verbose_name='文献标签')),
                ('literature_uploader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='文献上传者')),
            ],
            options={
                'verbose_name': '文献信息',
                'verbose_name_plural': '文献信息',
            },
        ),
    ]
