# Generated by Django 3.0.3 on 2020-03-17 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('literature', '0002_label_create_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='literature',
            name='filename',
            field=models.TextField(default='未上传文件', verbose_name='文献的文件名'),
        ),
    ]
