# Generated by Django 3.0.3 on 2020-03-21 21:52

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('literature', '0005_auto_20200319_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_literature',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='literature.Literature', verbose_name='评论的文献'),
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favorite_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='收藏时间')),
                ('favorite_literature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='literature.Literature', verbose_name='评论的文献')),
            ],
            options={
                'verbose_name': '收藏夹',
                'verbose_name_plural': '收藏夹',
            },
        ),
    ]
