# Generated by Django 3.0.3 on 2020-03-22 11:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('literature', '0006_auto_20200321_2152'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorite',
            name='favorite_user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='收藏夹的用户'),
        ),
    ]
