# Generated by Django 3.0.3 on 2020-03-22 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('literature', '0007_favorite_favorite_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='literature',
            name='filename',
            field=models.CharField(default='未上传文件', max_length=50, verbose_name='文献的文件名'),
        ),
    ]
