# Generated by Django 3.0.3 on 2020-03-11 20:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_name', models.CharField(max_length=100, verbose_name='反馈主题')),
                ('feedback_content', models.TextField(default='', verbose_name='反馈内容')),
                ('feedback_date', models.DateField(default=django.utils.timezone.now, verbose_name='反馈时间')),
                ('feedback_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '信息反馈',
                'verbose_name_plural': '信息反馈',
            },
        ),
    ]
