# Generated by Django 3.0.3 on 2020-03-12 12:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='feedback_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='反馈时间'),
        ),
    ]
