# Generated by Django 3.0.3 on 2020-03-15 14:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_auto_20200315_1246'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chat',
            options={'verbose_name': '讨论区', 'verbose_name_plural': '讨论区'},
        ),
        migrations.AlterField(
            model_name='chat',
            name='chat_name',
            field=models.CharField(max_length=100, unique=True, verbose_name='讨论区名称'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='create_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='讨论区创建时间'),
        ),
    ]
