# Generated by Django 3.0.3 on 2020-03-21 22:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0008_auto_20200321_2152'),
        ('base', '0006_auto_20200321_2152'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0003_auto_20200315_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='chat_user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='讨论区创建者'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='meeting',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='meeting.Meeting', verbose_name='讨论区的会议'),
        ),
        migrations.CreateModel(
            name='ChatArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_name', models.CharField(max_length=100, unique=True, verbose_name='闲聊区名称')),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='闲聊区创建时间')),
                ('chat_banji', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.Banji', verbose_name='班级闲聊区')),
                ('chat_major', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.Major', verbose_name='专业闲聊区')),
                ('chat_user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='闲聊区创建者')),
            ],
            options={
                'verbose_name': '闲聊区',
                'verbose_name_plural': '闲聊区',
            },
        ),
    ]
