# Generated by Django 3.0.3 on 2020-03-24 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_auto_20200321_2222'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='chat_start',
            field=models.IntegerField(default=0, verbose_name='讨论区开启标志'),
        ),
        migrations.AddField(
            model_name='chatarea',
            name='chat_start',
            field=models.IntegerField(default=0, verbose_name='闲聊区开启/关闭标志'),
        ),
    ]
