# Generated by Django 3.0.3 on 2020-03-25 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_auto_20200324_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='chat_start',
            field=models.IntegerField(choices=[(0, 0), (1, 1)], default=0, verbose_name='讨论区开启标志'),
        ),
        migrations.AlterField(
            model_name='chatarea',
            name='chat_start',
            field=models.IntegerField(choices=[(0, 0), (1, 1)], default=0, verbose_name='闲聊区开启/关闭标志'),
        ),
    ]
