# Generated by Django 3.0.3 on 2020-03-26 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_auto_20200325_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='chat_name',
            field=models.CharField(max_length=100, verbose_name='讨论区名称'),
        ),
    ]
