# Generated by Django 3.0.3 on 2020-03-27 13:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_auto_20200326_0905'),
    ]

    operations = [
        migrations.CreateModel(
            name='SensitiveWords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100, unique=True, verbose_name='敏感词汇')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='敏感词汇添加时间')),
            ],
            options={
                'verbose_name': '敏感词汇',
                'verbose_name_plural': '敏感词汇',
            },
        ),
    ]
