# Generated by Django 3.0.3 on 2020-04-16 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_sensitivewords'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='chat_start',
            field=models.IntegerField(choices=[(0, '开启'), (1, '关闭')], default=0, verbose_name='讨论区开启标志'),
        ),
        migrations.AlterField(
            model_name='chatarea',
            name='chat_start',
            field=models.IntegerField(choices=[(0, '开启'), (1, '关闭')], default=0, verbose_name='闲聊区开启/关闭标志'),
        ),
    ]
