# Generated by Django 3.0.3 on 2020-05-05 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_auto_20200416_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='chat_start',
            field=models.IntegerField(choices=[(1, '开启'), (0, '关闭')], default=0, verbose_name='讨论区开启标志'),
        ),
        migrations.AlterField(
            model_name='chatarea',
            name='chat_start',
            field=models.IntegerField(choices=[(1, '开启'), (0, '关闭')], default=0, verbose_name='闲聊区开启/关闭标志'),
        ),
    ]
