# Generated by Django 3.0.3 on 2020-03-22 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_auto_20200321_2152'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banji',
            options={'verbose_name': '班级', 'verbose_name_plural': '班级'},
        ),
        migrations.AlterModelOptions(
            name='department',
            options={'verbose_name': '学院', 'verbose_name_plural': '学院'},
        ),
        migrations.AlterModelOptions(
            name='major',
            options={'verbose_name': '专业', 'verbose_name_plural': '专业'},
        ),
        migrations.AlterField(
            model_name='banji',
            name='banji_name',
            field=models.CharField(default='', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='department_name',
            field=models.CharField(default='', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='lab',
            name='lab_name',
            field=models.CharField(default='', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='major',
            name='major_name',
            field=models.CharField(default='', max_length=50, unique=True),
        ),
    ]
