# Generated by Django 3.0.3 on 2020-03-24 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_auto_20200322_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.IntegerField(choices=[(0, 0), (1, 1), (2, 2)], default=0, verbose_name='身份标识(0:学生/1:老师/2:管理员)'),
        ),
    ]
