# Generated by Django 3.0.3 on 2020-04-16 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_auto_20200324_1518'),
    ]

    operations = [
        migrations.CreateModel(
            name='Duty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50, verbose_name='值班人员')),
                ('sex', models.IntegerField(choices=[(0, 0), (1, 1)], default=0, verbose_name='性别(0:男/1:女)')),
                ('phone', models.CharField(default='', max_length=11, verbose_name='电话')),
                ('week', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7)], default=0, verbose_name='值班时间')),
                ('lab', models.ManyToManyField(blank=True, to='base.Lab', verbose_name='值班地点')),
            ],
            options={
                'verbose_name': '实验室值班表',
                'verbose_name_plural': '实验室值班表',
            },
        ),
    ]
