# Generated by Django 3.0.3 on 2020-04-16 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_duty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='duty',
            name='sex',
            field=models.IntegerField(choices=[('男', 0), ('女', 1)], default=0, verbose_name='性别(0:男/1:女)'),
        ),
    ]
