# Generated by Django 3.0.3 on 2020-04-16 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_auto_20200416_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='duty',
            name='sex',
            field=models.IntegerField(choices=[(0, '女'), (1, '男')], default=0, verbose_name='性别(0:女/1:男)'),
        ),
        migrations.AlterField(
            model_name='duty',
            name='week',
            field=models.IntegerField(choices=[(1, '星期一'), (2, '星期二'), (3, '星期三'), (4, '星期四'), (5, '星期五'), (6, '星期六'), (7, '星期日')], default=0, verbose_name='值班时间'),
        ),
    ]
