# Generated by Django 3.0.3 on 2020-04-16 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_auto_20200416_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.IntegerField(choices=[(0, '学生'), (1, '老师'), (2, '管理员')], default=0, verbose_name='身份标识(0:学生/1:老师/2:管理员)'),
        ),
    ]
