# Generated by Django 3.0.3 on 2020-03-11 20:43

import ckeditor_uploader.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notice_name', models.TextField(default='通知', verbose_name='通知名称')),
                ('notice_issuer', models.TextField(default='超级管理员', verbose_name='发布人')),
                ('notice_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='发布时间')),
                ('notice_read', models.IntegerField(default=0, verbose_name='浏览人数')),
                ('notice_content', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='通知内容')),
            ],
            options={
                'verbose_name': '实验室通告',
                'verbose_name_plural': '实验室通告',
            },
        ),
    ]
