# Generated by Django 3.0.3 on 2020-03-22 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='notice_issuer',
            field=models.CharField(default='超级管理员', max_length=30, verbose_name='发布人'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='notice_name',
            field=models.CharField(default='通知', max_length=100, verbose_name='通知名称'),
        ),
    ]
