# Generated by Django 3.0.3 on 2020-03-11 20:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting_name', models.CharField(max_length=100, unique=True, verbose_name='会议名字')),
                ('meeting_theme', models.TextField(default='', verbose_name='会议主题')),
                ('meeting_file', models.FileField(blank=True, upload_to='upload/files/', verbose_name='上传文件')),
                ('create_date', models.DateField(default=django.utils.timezone.now, verbose_name='会议创建时间')),
                ('meeting_banji', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Banji')),
                ('meeting_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '会议',
                'verbose_name_plural': '会议',
            },
        ),
    ]
