# Generated by Django 3.0.3 on 2020-03-12 12:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0003_auto_20200312_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='create_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='会议创建时间'),
        ),
    ]
