# Generated by Django 3.0.3 on 2020-03-12 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0004_auto_20200312_1239'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='filename',
            field=models.TextField(default='', verbose_name='文件名'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='filesize',
            field=models.IntegerField(default=0, verbose_name='文件大小'),
        ),
    ]
