# Generated by Django 3.0.3 on 2020-03-13 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0005_auto_20200312_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='filesize',
            field=models.IntegerField(blank=True, null=True, verbose_name='文件大小'),
        ),
    ]
