# Generated by Django 3.0.3 on 2020-03-15 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0006_auto_20200313_1011'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='boardmeeting',
            options={'verbose_name': '会议留言', 'verbose_name_plural': '会议留言'},
        ),
    ]
