# Generated by Django 3.0.3 on 2020-03-21 21:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0006_auto_20200321_2152'),
        ('meeting', '0007_auto_20200315_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardmeeting',
            name='meeting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meeting.Meeting', verbose_name='留言的会议'),
        ),
        migrations.AlterField(
            model_name='boardmeeting',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='留言用户'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='meeting_banji',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Banji', verbose_name='会议的班级'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='meeting_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='会议发布者'),
        ),
    ]
