# Generated by Django 3.0.3 on 2020-03-22 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0008_auto_20200321_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='filename',
            field=models.CharField(default='', max_length=50, verbose_name='文件名'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='meeting_name',
            field=models.CharField(max_length=50, unique=True, verbose_name='会议名字'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='meeting_theme',
            field=models.CharField(default='', max_length=50, verbose_name='会议主题'),
        ),
    ]
