# Generated by Django 3.0.3 on 2020-03-22 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0009_auto_20200322_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='meeting_name',
            field=models.CharField(max_length=50, verbose_name='会议名字'),
        ),
    ]
