# Generated by Django 3.0.3 on 2020-03-24 13:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('meeting', '0010_auto_20200322_2158'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sign', models.IntegerField(default=0, verbose_name='签到')),
                ('meeting', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='meeting.Meeting', verbose_name='会议')),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='参会人员')),
            ],
            options={
                'verbose_name': '会议人员',
                'verbose_name_plural': '会议人员',
            },
        ),
    ]
