# Generated by Django 3.0.3 on 2020-03-24 14:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0011_attendee'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendee',
            name='sign_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='签到时间'),
        ),
    ]
