# Generated by Django 3.0.3 on 2020-04-16 15:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('meeting', '0012_attendee_sign_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChooseStudent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choose', models.IntegerField(default=0, verbose_name='是否选择0:未选/1:已选')),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meeting.Meeting', verbose_name='对应的会议')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='选择的人员')),
            ],
            options={
                'verbose_name': '选择人员表',
                'verbose_name_plural': '选择人员表',
            },
        ),
    ]
