# Generated by Django 3.0.3 on 2020-04-16 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0013_choosestudent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='choosestudent',
            options={'verbose_name': '人员选择', 'verbose_name_plural': '人员选择'},
        ),
        migrations.AlterField(
            model_name='choosestudent',
            name='choose',
            field=models.IntegerField(choices=[(0, 0), (1, 1)], default=0, verbose_name='是否选择0:未选/1:已选'),
        ),
    ]
