# Generated by Django 3.0.3 on 2020-04-16 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0014_auto_20200416_1945'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendee',
            options={'verbose_name': '会议签到', 'verbose_name_plural': '会议签到'},
        ),
        migrations.AlterField(
            model_name='attendee',
            name='sign',
            field=models.IntegerField(choices=[(0, '未签到'), (1, '已签到')], default=0, verbose_name='签到0：未签到/1：已签到'),
        ),
        migrations.AlterField(
            model_name='choosestudent',
            name='choose',
            field=models.IntegerField(choices=[(0, '未选'), (1, '已选')], default=0, verbose_name='是否选择0:未选/1:已选'),
        ),
    ]
